version: "3"
services:
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  retweet:
    build:
      dockerfile: Dockerfile
      context: ./retweet
    container_name: retweet
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/retweet/node_modules

    env_file:
      - ./retweet/.env.dev
  tweet:
    build:
      dockerfile: Dockerfile
      context: ./tweet
    container_name: tweet
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/tweet/node_modules
    env_file:
      - ./tweet/.env.dev
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"

    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - retweet
      - tweet
      - user
    ports:
      - 80:80
